services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:7.6.0"
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: "confluentinc/cp-kafka:7.6.0"
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kyc-service:
    build:
      context: .
      dockerfile: services/providers/kyc/Dockerfile
    hostname: kyc-service
    container_name: kyc-service
    ports:
      - "8081:8081"
    volumes:
      - ./tests/usecases/kyc:/root/tests/usecases/kyc
    networks:
      - default

  consumer-service:
    build:
      context: .
      dockerfile: services/consumer/Dockerfile
    hostname: consumer-service
    container_name: consumer-service
    environment:
      # These environment variables will be picked up by the Go application
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092 # Internal Kafka addresses for other services
      SOAP_SERVICE_URL: http://kyc-service:8081/soap
    depends_on:
      - kafka
      - kyc-service
    networks:
      - default

  mountebank:
    image: bbyars/mountebank:2.9.2
    hostname: mountebank
    container_name: mountebank
    ports:
      - "2525:2525" # Mountebank's default HTTP port
    networks:
      - default
    command: start
    environment:
      MB_FLAGS: --ip 0.0.0.0
